apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ydata.ai
spec:
  group: ydata.ai
  names:
    kind: ydata
    listKind: YdataList
    plural: ydatas
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicas"]
          properties:
            replicas:
              type: "integer"
              minimum: 1