apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: ydatas.ydata.ai
spec:
  group: ydata.ai
  names:
    kind: "Ydata"
    singular: "ydata"
    plural: "ydatas"
    listKind: "Ydatas"
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicas"]
          properties:
            replicas:
              type: "integer"
              minimum: 1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []